
package vista;

import game.GameMaster;

import javax.swing.JLabel;

import javax.swing.JOptionPane;

import modelo.IA;
import modelo.Player;
import modelo.User;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import utils.NoManaException;

/**
 *
 * @author Usuario
 */
public class Window extends javax.swing.JFrame implements IWindow{

    private User user;
    private IA ia;
    private GameMaster gm;
    
    /** Creates new form Window */
    public Window() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        SouthPanel = new javax.swing.JPanel();
        PlayerIcon = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        deckText = new javax.swing.JLabel();
        userHpText = new javax.swing.JLabel();
        manaText = new javax.swing.JLabel();
        SouthAuxPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        firstCardText = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        secondCardText = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        thirdCardText = new javax.swing.JLabel();
        userHpBar = new javax.swing.JProgressBar();
        userHpBar1 = new javax.swing.JProgressBar();
        enemyHpText2 = new javax.swing.JLabel();
        blackbg1 = new javax.swing.JPanel();
        EndTurnButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel105 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        playerName1 = new javax.swing.JLabel();
        enemyHpText = new javax.swing.JLabel();
        enemyIcon = new javax.swing.JLabel();
        enemyHpText1 = new javax.swing.JLabel();
        enemyHpBar = new javax.swing.JProgressBar();
        enemyHpBar1 = new javax.swing.JProgressBar();
        EndLabel = new javax.swing.JLabel();
        EndLabel1 = new javax.swing.JLabel();
        blackbg = new javax.swing.JPanel();
        eventLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abyss Seeker's");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SouthPanel.setBackground(new java.awt.Color(255, 0, 51));
        SouthPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/pachicon.png"))); // NOI18N
        SouthPanel.add(PlayerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        playerName.setFont(new java.awt.Font("Rockwell", 2, 30)); // NOI18N
        playerName.setForeground(new java.awt.Color(255, 255, 255));
        playerName.setText("User");
        SouthPanel.add(playerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        deckText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        deckText.setForeground(new java.awt.Color(255, 255, 255));
        deckText.setText("Deck:  [20]");
        SouthPanel.add(deckText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, 30));

        userHpText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        userHpText.setForeground(new java.awt.Color(255, 255, 255));
        userHpText.setText("[200/300]");
        SouthPanel.add(userHpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 30));

        manaText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        manaText.setForeground(new java.awt.Color(255, 255, 255));
        manaText.setText("Mana: [6/6]");
        SouthPanel.add(manaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, -1));

        SouthAuxPanel.setBackground(new java.awt.Color(51, 51, 51));
        SouthAuxPanel.setLayout(new java.awt.GridLayout(3, 1));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setLayout(new java.awt.BorderLayout());

        firstCardText.setBackground(new java.awt.Color(102, 255, 102));
        firstCardText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        firstCardText.setForeground(new java.awt.Color(255, 255, 255));
        firstCardText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstCardText.setText("Daga de fuego [2]  ");
        firstCardText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstCardTextMouseClicked(evt);
            }
        });
        jPanel16.add(firstCardText, java.awt.BorderLayout.CENTER);

        SouthAuxPanel.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));
        jPanel17.setLayout(new java.awt.BorderLayout());

        secondCardText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        secondCardText.setForeground(new java.awt.Color(255, 255, 255));
        secondCardText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondCardText.setText("Curacion Menor [2]  ");
        secondCardText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondCardTextMouseClicked(evt);
            }
        });
        jPanel17.add(secondCardText, java.awt.BorderLayout.CENTER);

        SouthAuxPanel.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setLayout(new java.awt.BorderLayout());

        thirdCardText.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        thirdCardText.setForeground(new java.awt.Color(255, 255, 255));
        thirdCardText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        thirdCardText.setText("Espada Ignea [5]  ");
        thirdCardText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdCardTextMouseClicked(evt);
            }
        });
        jPanel18.add(thirdCardText, java.awt.BorderLayout.CENTER);

        SouthAuxPanel.add(jPanel18);

        SouthPanel.add(SouthAuxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 300, 150));

        userHpBar.setForeground(new java.awt.Color(0, 204, 102));
        userHpBar.setValue(50);
        userHpBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        userHpBar.setBorderPainted(false);
        SouthPanel.add(userHpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 124, 210, -1));

        userHpBar1.setForeground(new java.awt.Color(255, 204, 0));
        userHpBar1.setValue(50);
        userHpBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        userHpBar1.setBorderPainted(false);
        SouthPanel.add(userHpBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, -1));

        enemyHpText2.setBackground(new java.awt.Color(0, 0, 0));
        enemyHpText2.setFont(new java.awt.Font("Rockwell", 2, 20)); // NOI18N
        enemyHpText2.setForeground(new java.awt.Color(0, 204, 102));
        enemyHpText2.setText("HP");
        enemyHpText2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        enemyHpText2.setAlignmentY((float) 0.0);
        enemyHpText2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SouthPanel.add(enemyHpText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 122, 30, 20));

        blackbg1.setBackground(new java.awt.Color(12, 11, 11));
        blackbg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        SouthPanel.add(blackbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 148, 150));

        jPanel1.add(SouthPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 830, 150));

        EndTurnButton.setBackground(new java.awt.Color(255, 0, 102));
        EndTurnButton.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        EndTurnButton.setForeground(new java.awt.Color(255, 255, 255));
        EndTurnButton.setText(">>End Turn  ");
        EndTurnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        EndTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndTurnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EndTurnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 190, 60));

        ExitButton.setBackground(new java.awt.Color(255, 51, 0));
        ExitButton.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit Game");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 190, 50));

        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/drakeImage.png"))); // NOI18N
        jPanel1.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 290, 250));

        jLabel107.setIcon(new javax.swing.ImageIcon("D:\\JDeveloper\\mywork\\Cartas\\CardGame\\src\\vista\\drakeEnemyImage.png")); // NOI18N
        jPanel1.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jPanel15.setBackground(new java.awt.Color(12, 11, 11));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName1.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        playerName1.setForeground(new java.awt.Color(255, 255, 255));
        playerName1.setText("Enemy");
        jPanel15.add(playerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        enemyHpText.setFont(new java.awt.Font("Rockwell", 2, 21)); // NOI18N
        enemyHpText.setForeground(new java.awt.Color(255, 255, 255));
        enemyHpText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enemyHpText.setText("[200/300]");
        jPanel15.add(enemyHpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, -1));

        enemyIcon.setIcon(new javax.swing.ImageIcon("D:\\JDeveloper\\mywork\\Cartas\\CardGame\\src\\vista\\EnemyIcon.png")); // NOI18N
        jPanel15.add(enemyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 50));

        enemyHpText1.setBackground(new java.awt.Color(0, 0, 0));
        enemyHpText1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        enemyHpText1.setForeground(new java.awt.Color(204, 153, 0));
        enemyHpText1.setText("HP");
        enemyHpText1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        enemyHpText1.setAlignmentY((float) 0.0);
        enemyHpText1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel15.add(enemyHpText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 55, 30, 20));

        enemyHpBar.setForeground(new java.awt.Color(255, 204, 0));
        enemyHpBar.setValue(50);
        enemyHpBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        enemyHpBar.setBorderPainted(false);
        jPanel15.add(enemyHpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 320, -1));

        enemyHpBar1.setForeground(new java.awt.Color(255, 51, 204));
        enemyHpBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        enemyHpBar1.setBorderPainted(false);
        jPanel15.add(enemyHpBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 190, -1));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 90));

        EndLabel.setFont(new java.awt.Font("Rockwell", 2, 80)); // NOI18N
        EndLabel.setForeground(new java.awt.Color(255, 204, 0));
        EndLabel.setText("Derrota");
        jPanel1.add(EndLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 220, 280, 100));

        EndLabel1.setFont(new java.awt.Font("Rockwell", 2, 80)); // NOI18N
        EndLabel1.setForeground(new java.awt.Color(255, 102, 0));
        EndLabel1.setText("Derrota");
        jPanel1.add(EndLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 310, 130));

        blackbg.setBackground(new java.awt.Color(0, 0, 0));
        blackbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventLabel.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        eventLabel.setForeground(new java.awt.Color(102, 153, 0));
        eventLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventLabel.setText(">>Nicolas usa Daga de Fuego<<");
        blackbg.add(eventLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, -1));

        jPanel1.add(blackbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\JDeveloper\\mywork\\Cartas\\CardGame\\src\\vista\\bg.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }//GEN-END:initComponents

    private void EndTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndTurnButtonActionPerformed
        if (GameMaster.getEndFlag()!=1 && gm.getTurn()==0){
            gm.changeTurn();
            this.eventSign("");
            gm.iniciaTurno(ia);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EndTurnButtonActionPerformed

    private void firstCardTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstCardTextMouseClicked
        if (GameMaster.getEndFlag()!=1 && gm.getTurn() == 0){
            if (!this.firstCardText.getText().equals("")) {
                try {
                    gm.pickCard(1);
                    this.firstCardText.setText("");
                } catch (NoManaException e) {
                    JOptionPane.showMessageDialog(null, "No enough mana","Action not available",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_firstCardTextMouseClicked

    private void secondCardTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondCardTextMouseClicked
    if (GameMaster.getEndFlag()!=1 && gm.getTurn() == 0){
            if (!this.secondCardText.getText().equals("")) {
                try {
                    gm.pickCard(2);
                    this.secondCardText.setText("");
                } catch (NoManaException e) {
                    JOptionPane.showMessageDialog(null, "No enough mana","Action not available",JOptionPane.ERROR_MESSAGE);
                }  
            }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_secondCardTextMouseClicked

    private void thirdCardTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdCardTextMouseClicked
    if (GameMaster.getEndFlag()!=1 && gm.getTurn() == 0){
            if (!this.thirdCardText.getText().equals("")) {
                try {
                    gm.pickCard(3);
                    this.thirdCardText.setText("");
                } catch (NoManaException e) {
                    JOptionPane.showMessageDialog(null, "No enough mana","Action not available",JOptionPane.ERROR_MESSAGE);   
                }
            }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdCardTextMouseClicked

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EndLabel;
    private javax.swing.JLabel EndLabel1;
    private javax.swing.JButton EndTurnButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel PlayerIcon;
    private javax.swing.JPanel SouthAuxPanel;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel blackbg;
    private javax.swing.JPanel blackbg1;
    private javax.swing.JLabel deckText;
    private javax.swing.JProgressBar enemyHpBar;
    private javax.swing.JProgressBar enemyHpBar1;
    private javax.swing.JLabel enemyHpText;
    private javax.swing.JLabel enemyHpText1;
    private javax.swing.JLabel enemyHpText2;
    private javax.swing.JLabel enemyIcon;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JLabel firstCardText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JLabel manaText;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerName1;
    private javax.swing.JLabel secondCardText;
    private javax.swing.JLabel thirdCardText;
    private javax.swing.JProgressBar userHpBar;
    private javax.swing.JProgressBar userHpBar1;
    private javax.swing.JLabel userHpText;
    // End of variables declaration//GEN-END:variables



    @Override
    public void arranca() {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    @Override
    public void updateStats() {
        this.manaText.setText("Mana:  ["+user.getMana()+"/"+(user.getMaxMana()-1)+"]");
        this.deckText.setText("Deck:  ["+user.getDeckCount()+"]");
        this.userHpText.setText("["+user.getHp()+"/300]");
        this.enemyHpText.setText("["+ia.getHp()+"/300]");
        if (user.getHp()>200){
            this.userHpBar.setValue(100);
            this.userHpBar1.setValue((user.getHp()-200));
        }
        else{
            this.userHpBar.setValue((int)(user.getHp()*0.5));
            this.userHpBar1.setValue(0);
        }
        if (ia.getHp()>200){
            this.enemyHpBar.setValue(100);
            this.enemyHpBar1.setValue((ia.getHp()-200));
        }
        else{
            this.enemyHpBar.setValue((int)(ia.getHp()*0.5));
            this.enemyHpBar1.setValue(0);
        }
    }

    @Override
    public void endSign(String sign) {
        this.EndLabel.setText(sign);
        this.EndLabel1.setText(sign);
        this.updateStats();
    }

    @Override
    public void eventSign(String sign) {
        this.blackbg.setVisible(true);
        this.eventLabel.setText(sign);
        this.updateStats();
    }
    
    @Override
    public void waitSign() {
        this.blackbg.setVisible(false);
    }

    @Override
    public void setCard1(String string) {
        this.firstCardText.setText(string);
    }

    @Override
    public void setCard2(String string) {
        this.secondCardText.setText(string); 
    }

    @Override
    public void setCard3(String string) {
        this.thirdCardText.setText(string);
    }

    public void putCard(String string,int index) {
       if (index==1)
        this.firstCardText.setText(string+"   ");
       else{
           if (index==2)
            this.secondCardText.setText(string+"   ");
           else{
            this.thirdCardText.setText(string+"   ");
           }
       }
    }

    @Override
    public void setUser(Player user) {
        this.user = (User)user;
    }

    @Override
    public void setIa(Player ia) {
        this.ia = (IA)ia;
    }

    public void setGm(GameMaster gm) {
        this.gm = gm;
    }

    @Override
    public void finalizar() {
        this.jPanel1.setEnabled(false);
    }

    @Override
    public void setExitButton(boolean bool) {
        this.ExitButton.setVisible(bool);
    }
}
